const express = require('express');
const cors = require('cors');
const app = express();

app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 7000;

// Direct mapping using your exact model names
const modelMetadata = {
    'gemini-3.6-flash': { 
        name: 'Arabic Fusha Subtitles (Gemini 3.6 Flash)', 
        apiModel: 'gemini-3.6-flash', 
        logo: 'https://i.imgur.com/h7eKUdF.png', 
        background: 'https://i.imgur.com/KNLQb24.jpeg' 
    },
    'gemini-3.5-flash-lite': { 
        name: 'Arabic Fusha Subtitles (Gemini 3.5 Flash Lite)', 
        apiModel: 'gemini-3.5-flash-lite', 
        logo: 'https://i.imgur.com/h7eKUdF.png', 
        background: 'https://i.imgur.com/KNLQb24.jpeg' 
    },
    'gemini-3.1-pro': { 
        name: 'Arabic Fusha Subtitles (Gemini 3.1 Pro)', 
        apiModel: 'gemini-3.1-pro', 
        logo: 'https://i.imgur.com/h7eKUdF.png', 
        background: 'https://i.imgur.com/KNLQb24.jpeg' 
    }
};

// 0. Serve the Built-In Frontend Website Dashboard at Root
app.get('/', (req, res) => {
    res.send(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arabic Fusha Subtitles Addon Configuration</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
        .card { background: #1e293b; padding: 2.5rem; border-radius: 1rem; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.5); width: 100%; max-width: 450px; }
        h1 { font-size: 1.5rem; margin-bottom: 0.5rem; color: #38bdf8; }
        p { color: #94a3b8; font-size: 0.9rem; margin-bottom: 1.5rem; }
        label { display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 0.5rem; color: #cbd5e1; }
        input, select { width: 100%; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid #334155; background: #0f172a; color: #fff; margin-bottom: 1.25rem; font-size: 1rem; box-sizing: border-box; }
        input:focus, select:focus { outline: none; border-color: #38bdf8; }
        .btn { display: block; width: 100%; padding: 0.75rem; background: #0284c7; color: white; border: none; border-radius: 0.5rem; font-size: 1rem; font-weight: 600; cursor: pointer; text-align: center; text-decoration: none; box-sizing: border-box; transition: background 0.2s; }
        .btn:hover { background: #0369a1; }
    </style>
</head>
<body>
    <div class="card">
        <h1>Arabic Fusha Subtitles</h1>
        <p>Configure your Gemini AI cinematic translator addon for Stremio.</p>
        
        <label for="apiKey">Gemini API Key</label>
        <input type="password" id="apiKey" placeholder="Paste your AIzaSy... key here">
        
        <label for="model">Gemini Model</label>
        <select id="model">
            <option value="gemini-3.6-flash">Gemini 3.6 Flash</option>
            <option value="gemini-3.5-flash-lite">Gemini 3.5 Flash Lite</option>
            <option value="gemini-3.1-pro">Gemini 3.1 Pro</option>
        </select>
        
        <button class="btn" onclick="installAddon()">Install in Stremio</button>
    </div>
    <script>
        function installAddon() {
            const apiKey = document.getElementById('apiKey').value.trim();
            const model = document.getElementById('model').value;
            if (!apiKey) {
                alert('Please enter your Gemini API Key first!');
                return;
            }
            const host = window.location.host;
            const stremioUrl = 'stremio://' + host + '/' + apiKey + '/enabled/' + model + '/manifest.json';
            window.location.href = stremioUrl;
        }
    </script>
</body>
</html>`);
});

// 1. Dynamic Manifest Route
app.get('/:apiKey/:config/:model/manifest.json', (req, res) => {
    const { apiKey, config, model } = req.params;

    if (config === 'disabled') {
        return res.json({
            id: 'org.arabic.fusha.subtitles.disabled',
            version: '2.2.0',
            name: 'Arabic Fusha Subtitle [Disabled]',
            description: 'Arabic subtitles are currently disabled from the dashboard.',
            types: ['movie', 'series'],
            resources: ['subtitles'],
            catalogs: [],
            idPrefixes: ['tt']
        });
    }

    const meta = modelMetadata[model] || modelMetadata['gemini-3.6-flash'];

    const manifest = {
        id: `org.arabic.fusha.subtitles.${model}`,
        version: '2.2.0',
        name: meta.name,
        description: 'Real-time AI-powered Fusha Arabic cinematic subtitles generated by Google Gemini from actual dialogues.',
        types: ['movie', 'series'],
        resources: ['subtitles'],
        catalogs: [],
        idPrefixes: ['tt'],
        logo: meta.logo,
        background: meta.background,
        behaviorHints: {
            configurable: true,
            configurationRequired: false
        }
    };

    res.json(manifest);
});

// 2. Subtitles Endpoint
app.get('/:apiKey/:config/:model/subtitles/:type/:id/:extra?.json', async (req, res) => {
    const { apiKey, config, model, type, id } = req.params;

    if (config === 'disabled' || !apiKey || apiKey === 'DEFAULT_SUB_KEY') {
        return res.json({ subtitles: [] });
    }

    try {
        console.log(`[Stremio Subtitle Request] Type: ${type}, ID: ${id}, Model: ${model}`);
        const baseUrl = `${req.protocol}://${req.get('host')}`;

        const subtitlesList = [
            {
                id: `${id}-ar-fusha-${model}`,
                url: `${baseUrl}/proxy-subtitle?id=${id}&model=${model}&apiKey=${apiKey}&type=${type}`,
                lang: 'ara',
                subtitles: `Arabic Fusha AI (${model})`
            }
        ];

        res.json({ subtitles: subtitlesList });
    } catch (error) {
        console.error("Error handling subtitle request:", error);
        res.json({ subtitles: [] });
    }
});

// 3. Real AI Translation Proxy Endpoint
app.get('/proxy-subtitle', async (req, res) => {
    const { id, model, apiKey, type } = req.query;
    console.log(`[AI Translation] Generating accurate Fusha Arabic subtitles for ID: ${id} (${type}) using model: ${model}`);

    const meta = modelMetadata[model] || modelMetadata['gemini-3.6-flash'];
    const geminiModel = meta.apiModel;

    try {
        const prompt = `You are a professional master subtitle synchronization engineer and cinematic translator. Generate a complete, high-accuracy WebVTT subtitle file in standard literary Arabic Fusha (العربية الفصحى) for IMDb ID ${id} (${type}).

CRITICAL INSTRUCTIONS TO PREVENT ERRORS:
1. STRICT DIALOGUE ACCURACY: Translate ONLY the real, actual spoken dialogue and words spoken by characters in this specific film or episode. Do NOT hallucinate, invent, or create fake conversations, filler words, or extra lines that are not part of the actual script.
2. ABSOLUTELY NO DEAF/HARD-OF-HEARING CAPTIONS: Do NOT include sound effects, background audio tags, music descriptions, or non-verbal noise markers (e.g., no [Music playing], no [Sighs]). Only translate spoken words.
3. PERFECT TIMING: Timestamps must be millisecond-precise, perfectly synchronized to match the exact moment characters speak.
4. FORMAT: Output ONLY raw WebVTT content starting with "WEBVTT". Do NOT wrap the response in markdown code blocks (\`\`\`vtt ... \`\`\`). No conversational text, intro, or outro.`;

        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: [{ parts: [{ text: prompt }] }]
            })
        });

        const data = await response.json();

        if (data.candidates && data.candidates[0]?.content?.parts?.[0]?.text) {
            let vttText = data.candidates[0].content.parts[0].text;
            vttText = vttText.replace(/^```[a-z]*\n?/i, '').replace(/```\s*$/, '').trim();

            res.setHeader('Content-Type', 'text/vtt; charset=utf-8');
            return res.send(vttText);
        } else {
            console.error("Gemini API Error:", data);
            throw new Error(data.error?.message || "Gemini API returned an invalid response.");
        }
    } catch (error) {
        console.error("AI Translation Failed:", error);
        res.setHeader('Content-Type', 'text/vtt; charset=utf-8');
        res.send(`WEBVTT\n\n1\n00:00:01.000 --> 00:00:08.000\n[خطأ في توليد الترجمة بواسطة الذكاء الاصطناعي]\n${error.message}`);
    }
});

// Bind to 0.0.0.0 for Railway
app.listen(PORT, '0.0.0.0', () => {
    console.log(`🚀 Live AI Arabic Fusha Subtitle Server running on port ${PORT}`);
});
